# -*- coding: utf-8 -*-
"""SP_AIE23121_LAB3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RIezSL3azhslHRonVlo9tcML2X0bPQTS
"""

!pip install librosa soundfile transformers torch torchaudio

!pip install pydub
!apt-get install ffmpeg

from pydub import AudioSegment

audio = AudioSegment.from_file("/content/lab3_sentence1.m4a")
audio = audio.set_channels(1).set_frame_rate(16000)

audio.export("/content/lab3_sentence1.wav", format="wav")

from pydub import AudioSegment

audio = AudioSegment.from_file("/content/lab3_sentence2.m4a")
audio = audio.set_channels(1).set_frame_rate(16000)

audio.export("/content/lab3_sentence2.wav", format="wav")

import librosa
import numpy as np
import matplotlib.pyplot as plt
import torch
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC

processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")
model.eval()

audio_path = "/content/lab3_sentence1.wav"

signal, sr = librosa.load(audio_path, sr=16000, mono=True)

duration = len(signal) / sr
print("Duration:", duration, "seconds")

plt.figure(figsize=(12,4))
plt.plot(signal)
plt.title("Speech Waveform")
plt.xlabel("Samples")
plt.ylabel("Amplitude")
plt.show()

inputs = processor(signal, sampling_rate=16000, return_tensors="pt")

with torch.no_grad():
    logits = model(inputs.input_values).logits

pred_ids = torch.argmax(logits, dim=-1)
tokens = processor.batch_decode(pred_ids)[0]

print("Recognized tokens:")
print(tokens)

num_tokens = len(tokens.replace(" ", ""))
segment_duration = duration / num_tokens

segments = []
start = 0

for i, ch in enumerate(tokens.replace(" ", "")):
    end = start + segment_duration
    s_idx = int(start * sr)
    e_idx = int(end * sr)
    segments.append((ch, signal[s_idx:e_idx]))
    start = end

for i, (ph, seg) in enumerate(segments[:8]):
    plt.figure(figsize=(4,2))
    plt.plot(seg)
    plt.title(f"Phoneme {i+1}: {ph}")
    plt.xlabel("Samples")
    plt.ylabel("Amplitude")
    plt.show()

voiced = segments[2][1]      # vowel-like
unvoiced = segments[6][1]    # fricative-like

plt.figure(figsize=(10,3))
plt.subplot(1,2,1)
plt.plot(voiced)
plt.title("Voiced Phoneme")

plt.subplot(1,2,2)
plt.plot(unvoiced)
plt.title("Unvoiced Phoneme")
plt.show()

"""OBJECTIVE- 2

"""

audio_path2 = "/content/lab3_sentence2.wav"
signal2, sr2 = librosa.load(audio_path2, sr=16000, mono=True)

inputs2 = processor(signal2, sampling_rate=16000, return_tensors="pt")

with torch.no_grad():
    logits2 = model(inputs2.input_values).logits

pred_ids2 = torch.argmax(logits2, dim=-1)
tokens2 = processor.batch_decode(pred_ids2)[0]

print(tokens2)

duration2 = len(signal2)/sr2
segment_dur2 = duration2 / len(tokens2.replace(" ", ""))

segments2 = []
start = 0
for ch in tokens2.replace(" ", ""):
    end = start + segment_dur2
    segments2.append(signal2[int(start*sr2):int(end*sr2)])
    start = end

fricative = segments2[1]   # /s/ or /ʃ/
approximant = segments2[-1]  # /j/

plt.figure(figsize=(10,3))
plt.subplot(1,2,1)
plt.plot(fricative)
plt.title("Fricative")

plt.subplot(1,2,2)
plt.plot(approximant)
plt.title("Approximant")
plt.show()

"""INFERENCES AND RESULTS

"""

import numpy as np

def rms_energy(signal):
    return np.sqrt(np.mean(signal**2))

def zero_crossing_rate(signal):
    return np.mean(np.abs(np.diff(np.sign(signal)))) / 2

def periodicity_estimate(signal):
    autocorr = np.correlate(signal, signal, mode='full')
    autocorr = autocorr[len(autocorr)//2:]
    peaks = np.where((autocorr[1:-1] > autocorr[:-2]) & (autocorr[1:-1] > autocorr[2:]))[0]
    return len(peaks)

voiced_energy = rms_energy(voiced)
unvoiced_energy = rms_energy(unvoiced)

voiced_zcr = zero_crossing_rate(voiced)
unvoiced_zcr = zero_crossing_rate(unvoiced)

voiced_periodicity = periodicity_estimate(voiced)
unvoiced_periodicity = periodicity_estimate(unvoiced)

print("---- VOICED vs UNVOICED PHONEME ANALYSIS ----\n")

print(f"Voiced phoneme RMS energy: {voiced_energy:.4f}")
print(f"Unvoiced phoneme RMS energy: {unvoiced_energy:.4f}\n")

if voiced_energy > unvoiced_energy:
    print("Inference: The voiced phoneme exhibits higher energy, indicating strong vocal fold vibration.")
else:
    print("Inference: The unvoiced phoneme shows comparable energy, which is atypical for unvoiced sounds.")

print()

print(f"Voiced phoneme Zero Crossing Rate: {voiced_zcr:.4f}")
print(f"Unvoiced phoneme Zero Crossing Rate: {unvoiced_zcr:.4f}\n")

if voiced_zcr < unvoiced_zcr:
    print("Inference: Lower zero crossing rate in voiced phoneme indicates periodic structure.")
    print("Inference: Higher zero crossing rate in unvoiced phoneme indicates noise-like behavior.")
else:
    print("Inference: Zero crossing trends do not follow typical voiced-unvoiced behavior.")

print()

print(f"Estimated periodic peaks (Voiced): {voiced_periodicity}")
print(f"Estimated periodic peaks (Unvoiced): {unvoiced_periodicity}\n")

if voiced_periodicity > unvoiced_periodicity:
    print("Inference: Voiced phoneme shows clear periodicity due to vocal fold vibration.")
    print("Inference: Unvoiced phoneme lacks periodicity, confirming absence of voicing.")
else:
    print("Inference: Periodicity pattern is weak, possibly due to short segment length.")

fric_energy = rms_energy(fricative)
app_energy = rms_energy(approximant)

fric_zcr = zero_crossing_rate(fricative)
app_zcr = zero_crossing_rate(approximant)

fric_periodicity = periodicity_estimate(fricative)
app_periodicity = periodicity_estimate(approximant)

print("\n---- FRICATIVE vs APPROXIMANT ANALYSIS ----\n")

print(f"Fricative RMS energy: {fric_energy:.4f}")
print(f"Approximant RMS energy: {app_energy:.4f}\n")

print(f"Fricative Zero Crossing Rate: {fric_zcr:.4f}")
print(f"Approximant Zero Crossing Rate: {app_zcr:.4f}\n")

if fric_zcr > app_zcr:
    print("Inference: Fricative exhibits high zero crossing rate, indicating turbulent airflow.")
    print("Inference: Approximant exhibits smoother waveform with lower turbulence.")
else:
    print("Inference: Zero crossing behavior is inconclusive.")

print()

print(f"Fricative periodicity estimate: {fric_periodicity}")
print(f"Approximant periodicity estimate: {app_periodicity}\n")

if app_periodicity > fric_periodicity:
    print("Inference: Approximant shows periodic structure due to partial vocal fold vibration.")
    print("Inference: Fricative lacks periodicity due to constricted airflow.")
else:
    print("Inference: Periodicity contrast is weak, possibly due to articulation variation.")

print()

print("Conceptual Inference:")
print("Fricatives correspond to high Reynolds number flow due to narrow constriction and turbulent airflow.")
print("Approximants correspond to low Reynolds number flow due to smoother, laminar airflow.")